[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]

[workspace.dependencies]
hdi = "=0.2.3"
hdk = "=0.1.3"
holochain_integrity_types = "=0.2.1"
serde = "=1.0.163"

[workspace.dependencies.converge]
path = "dnas/converge/zomes/coordinator/converge"

[workspace.dependencies.converge_integrity]
path = "dnas/converge/zomes/integrity/converge"

[workspace.dependencies.profiles]
path = "dnas/converge/zomes/coordinator/profiles"

[workspace.dependencies.profiles_integrity]
path = "dnas/converge/zomes/integrity/profiles"
